Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ex2_path = Path('example2-reduced')

dark_90 = CCDData.read(ex2_path / 'combined_dark_90.000.fit')
dark_1000 = CCDData.read('combined_dark_exposure_1000.0.fit.bz2')
dark_1000 = ccdp.trim_image(dark_1000[:, :4096])

dark_90 = dark_90.multiply(1.5 * u.electron / u.adu).divide(90 * u.second)
dark_1000 = dark_1000.multiply(1.5 * u.electron / u.adu).divide(1000 * u.second)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m ex2_path [38;5;241m=[39m Path([38;5;124m'[39m[38;5;124mexample2-reduced[39m[38;5;124m'[39m)
[1;32m      3[0m dark_90 [38;5;241m=[39m CCDData[38;5;241m.[39mread(ex2_path [38;5;241m/[39m [38;5;124m'[39m[38;5;124mcombined_dark_90.000.fit[39m[38;5;124m'[39m)
[0;32m----> 4[0m dark_1000 [38;5;241m=[39m [43mCCDData[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mcombined_dark_exposure_1000.0.fit.bz2[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      5[0m dark_1000 [38;5;241m=[39m ccdp[38;5;241m.[39mtrim_image(dark_1000[:, :[38;5;241m4096[39m])
[1;32m      7[0m dark_90 [38;5;241m=[39m dark_90[38;5;241m.[39mmultiply([38;5;241m1.5[39m [38;5;241m*[39m u[38;5;241m.[39melectron [38;5;241m/[39m u[38;5;241m.[39madu)[38;5;241m.[39mdivide([38;5;241m90[39m [38;5;241m*[39m u[38;5;241m.[39msecond)

File [0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/astropy/nddata/mixins/ndio.py:59[0m, in [0;36mNDDataRead.__call__[0;34m(self, *args, **kwargs)[0m
[1;32m     58[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m---> 59[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mregistry[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_cls[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/astropy/io/registry/core.py:184[0m, in [0;36mUnifiedInputRegistry.read[0;34m(self, cls, format, cache, *args, **kwargs)[0m
[1;32m    182[0m [38;5;28;01mtry[39;00m:
[1;32m    183[0m     ctx [38;5;241m=[39m get_readable_fileobj(args[[38;5;241m0[39m], encoding[38;5;241m=[39m[38;5;124m'[39m[38;5;124mbinary[39m[38;5;124m'[39m, cache[38;5;241m=[39mcache)
[0;32m--> 184[0m     fileobj [38;5;241m=[39m [43mctx[49m[38;5;241;43m.[39;49m[38;5;21;43m__enter__[39;49m[43m([49m[43m)[49m
[1;32m    185[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[1;32m    186[0m     [38;5;28;01mraise[39;00m

File [0;32m/usr/share/miniconda/envs/test/lib/python3.8/contextlib.py:113[0m, in [0;36m_GeneratorContextManager.__enter__[0;34m(self)[0m
[1;32m    111[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39margs, [38;5;28mself[39m[38;5;241m.[39mkwds, [38;5;28mself[39m[38;5;241m.[39mfunc
[1;32m    112[0m [38;5;28;01mtry[39;00m:
[0;32m--> 113[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mnext[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgen[49m[43m)[49m
[1;32m    114[0m [38;5;28;01mexcept[39;00m [38;5;167;01mStopIteration[39;00m:
[1;32m    115[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124m"[39m[38;5;124mgenerator didn[39m[38;5;124m'[39m[38;5;124mt yield[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;28mNone[39m

File [0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/astropy/utils/data.py:271[0m, in [0;36mget_readable_fileobj[0;34m(name_or_obj, encoding, cache, show_progress, remote_timeout, sources, http_headers)[0m
[1;32m    266[0m [38;5;28;01mif[39;00m is_url:
[1;32m    267[0m     name_or_obj [38;5;241m=[39m download_file(
[1;32m    268[0m         name_or_obj, cache[38;5;241m=[39mcache, show_progress[38;5;241m=[39mshow_progress,
[1;32m    269[0m         timeout[38;5;241m=[39mremote_timeout, sources[38;5;241m=[39msources,
[1;32m    270[0m         http_headers[38;5;241m=[39mhttp_headers)
[0;32m--> 271[0m fileobj [38;5;241m=[39m [43mio[49m[38;5;241;43m.[39;49m[43mFileIO[49m[43m([49m[43mname_or_obj[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    272[0m [38;5;28;01mif[39;00m is_url [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m cache:
[1;32m    273[0m     delete_fds[38;5;241m.[39mappend(fileobj)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'combined_dark_exposure_1000.0.fit.bz2'
FileNotFoundError: [Errno 2] No such file or directory: 'combined_dark_exposure_1000.0.fit.bz2'

